name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Change to project directory
      run: cd /home/daw1/Escritorio/EIAS/EIASserver

    - name: Pull latest changes
      run: git pull origin main

    - name: Install dependencies
      run: npm install

    - name: Restart
      run: restart all
