name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Obtiene todo el historial de commits

    - name: Change to project directory and pull latest changes
      run: |
        cd /home/daw1/Escritorio/EIAS/EIASserver
        git pull origin main

    - name: Install dependencies
      run: |
        cd /home/daw1/Escritorio/EIAS/EIASserver
        npm install

    - name: Restart
      run: |
        cd /home/daw1/Escritorio/EIAS/EIASserver
        pm2 restart all
